AWSTemplateFormatVersion: "2010-09-09"
Description: Update Launch Template + ASG for Sahil Cloud Project (Fix EC2 Health)

Parameters:
  VpcId:
    Type: String
    Default: vpc-00e9c6155d205bbf0

  PublicSubnet1:
    Type: String
    Default: subnet-030849cb746d7d479

  PublicSubnet2:
    Type: String
    Default: subnet-0e6685aa2b2b2ddb2

  PrivateSubnet1:
    Type: String
    Default: subnet-0f50eec8475882449

  PrivateSubnet2:
    Type: String
    Default: subnet-00460d519b0037dcd

  DBUsername:
    Type: String
    Default: sahil

  DBPassword:
    Type: String
    NoEcho: true
    Default: Sahil123!

Resources:

  ########################################
  # SECURITY GROUPS (unchanged)
  ########################################

  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref ALBSG
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ########################################
  # ALB + TG + Listener (unchanged)
  ########################################

  MyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref ALBSG
      Scheme: internet-facing
      Type: application

  MyTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: "/"
      HealthCheckProtocol: HTTP

  MyListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup

  ########################################
  # UPDATED LAUNCH TEMPLATE  (THIS FIXES EC2)
  ########################################

  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t3.micro
        ImageId: ami-0fc5d935ebf8bc3bc   # Amazon Linux 2 (N. Virginia)
        SecurityGroupIds:
          - !Ref EC2SG
        UserData:
          Fn::Base64: |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            echo "<h1>Sahil Cloud Project — Apache is running!</h1>" > /var/www/html/index.html

  ########################################
  # UPDATED AUTO SCALING GROUP  (unchanged except LT version)
  ########################################

  MyASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      MinSize: "1"
      MaxSize: "2"
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref MyLaunchTemplate
        Version: !GetAtt MyLaunchTemplate.LatestVersionNumber
      TargetGroupARNs:
        - !Ref MyTargetGroup

Outputs:
  ALBURL:
    Description: Application Load Balancer URL
    Value: !GetAtt MyALB.DNSName
